# Shared config applied to all services
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.expensetracker: DEBUG

app:
  jwt:
    secret: KESYsfa03zyiBQrCkyssfZOAd+HVhM88XTzQr7kjpfw=
    expiry-seconds: 86400
